action.configuration.coolifly_run_terminal_command:
  type: mapping
  label: 'Configuration for "Run Terminal Command" action'
  mapping:
    command-params:
      type: string
      label: Command Params
