<?php

/**
 * @file
 * ECA module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\eca\Event\TriggerEvent;
use Drupal\eca\PluginManager\Action;
use Drupal\eca\Service\ContentEntityTypes;

/**
 * Implements hook_ENTITY_TYPE_insert() for action entities.
 */
function eca_action_insert(EntityInterface $entity): void {
  Action::get()->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_update() for action entities.
 */
function eca_action_update(EntityInterface $entity): void {
  Action::get()->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_delete() for action entities.
 */
function eca_action_delete(EntityInterface $entity): void {
  Action::get()->clearCachedDefinitions();
}

/**
 * Provides the trigger event service.
 *
 * @return \Drupal\eca\Event\TriggerEvent
 *   The trigger event service.
 */
function _eca_trigger_event(): TriggerEvent {
  return \Drupal::service('eca.trigger_event');
}

/**
 * Provides the content entity types service.
 *
 * @return \Drupal\eca\Service\ContentEntityTypes
 *   The content entity types service.
 */
function _eca_content_entity_types(): ContentEntityTypes {
  return \Drupal::service('eca.service.content_entity_types');
}
