<?php

/**
 * @file
 * Contains websocket_comments.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function websocket_comments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the websocket_comments module.
    case 'help.page.websocket_comments':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Real-time comments over Websocket') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function websocket_comments_theme() {
  return [
    'websocket_comments' => [
      'render element' => 'children',
    ],
  ];
}
